# config/meta.yml
meta_title: "Mediaclasse"
meta_description: "TODO"
meta_image: "image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "https://twitter.com/mediaclassefr?lang=fr" # indispensable pour les Twitter Cards
