# config/meta.yml
meta_title: "Mediaclasse"
meta_description: "La littérature française analysée et illustrée en vidéo pour les lycéens, les étudiants en Lettres, et tous les passionnés de culture !"
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@mediaclassefr" # indispensable pour les Twitter Cards
