# config/meta.yml
meta_title: "Mediaclasse"
meta_description: "Commentaires composés pour le collège et le lycée avec les meilleures méthodes pédagogiques en vidéo"
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@mediaclassefr" # indispensable pour les Twitter Cards
