# config/meta.yml
meta_title: "Mediaclasse"
meta_description: "Les grands classiques de la littérature française résumés, analysés et illustrés en vidéo pour les lycéens, les étudiants en Lettres, et tous les passionnés de culture ! Ce sont des cours en ligne sous forme de vidéos. Mes explications linéaires, mes commentaires composés et mes méthodologies sont spécialement conçues pour le baccalauréat de Français, les classes Prepa, le CAPES et l'Agrégation de Lettres Modernes."
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@mediaclassefr" # indispensable pour les Twitter Cards
